version: '3.9'
services:
  mongodb:
    image: mongo:7
    container_name: fincy_mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - fincy_mongo_data:/data/db

volumes:
  fincy_mongo_data:
